# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default=320, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
